### DC

In [1]:
import math

def DC_table(fila,columna):
    if fila == 0:
        return 0
    if columna >= 2**(fila-1):
        return columna
    else:
        return -(2**fila)+1+columna
   
   
def DC_table_inv(num):
    if num == 0:
        return (0,0)
    fila = math.floor(math.log2(abs(num)))+1
    if num > 0:
        columna = num
    else:
        columna = num +(2**fila)-1
    return fila,columna

In [26]:
def DC_encoder(listaDC):
    lista_diff = [listaDC[0]]
    for i in range(1,len(listaDC)):
        lista_diff.append(listaDC[i] - listaDC[i-1])
    res = ""
    for elem in lista_diff:
        (f,c) = DC_table_inv(elem)
        bin_f = "1"*f+"0"
        bin_c = ""
        if f != 0: bin_c = '{0:0b}'.format(c).zfill(f)
        res += bin_f + bin_c
    return res

def DC_decoder(bin_DC):
    res = []
    i = 0
    while i < len(bin_DC):
        f = 0
        c = 0
        bit = bin_DC[i]
        while bit == "1":
            f+=1
            i+=1
            bit = bin_DC[i]
        i+=1#skip the zero
        if f == 0:
            c = 0
        else:
            c = int(bin_DC[i:i+f],2)
        i+=f
        diff = DC_table(f,c)
        num = diff
        if res != []: num += res[-1]
        res.append(num)
    return res
        

In [131]:
import functools
#ENCODER TEST
listaDC = [981, 840, 936, 870, 925, 931, 973, 870, 951, 951, 843, 869, 881, 996, 803, 840, 1045, 951, 905, 1024, 812, 1035, 959, 1010, 954, 1018, 915, 863, 1011, 1022, 882, 908, 949, 889, 866]
encoded = DC_encoder(listaDC)
print(encoded)
decoded = DC_decoder(encoded)
print(decoded)
if functools.reduce(lambda i, j : i and j, map(lambda m, k: m == k, listaDC, decoded), True) : 
    print ("The lists are identical")
else :
    print ("The lists are not identical")

1111111111011110101011111111100111001011111110110000011111110011110111111101101111110110111111010101011111110001100011111110101000101111111000100111111101101011110110011111110111001111111111000111110111111010010111111111011001101111111100100001111111001000111111110111011111111111000101011111111110110111111111111001100111111110110011111111000011111111110100000011111110001100011111100010111111111101001010011110101111111111001110011111110110101111110101001111111000001111111001000
[981, 840, 936, 870, 925, 931, 973, 870, 951, 951, 843, 869, 881, 996, 803, 840, 1045, 951, 905, 1024, 812, 1035, 959, 1010, 954, 1018, 915, 863, 1011, 1022, 882, 908, 949, 889, 866]
The lists are identical


In [23]:
a = "1111111101110101011111110101001111111110010111111111100001011111111011000101111001111111111011001001111110011001011111111001110001111111110110100101111000011111110001000111111000011011111110111001111111111001111101111111100010110111111110110111001111111100100010111111110101111011111110101101111111111001011101111111011000111111111010000011111101111111111001000111111110011110111111100110101111110101100111111011010011100101111110001100111111011010111111001101111101110111111110010111001111111010110011111111010010111111111100100111111111101000111111110100000111111101101011111111110010101001111110101110"
b = "1111111101110101011111110101001111111110010111111111100001011111111011000101111001111111111011001001111110011001011111111001110001111111110110100101111000011111110001000111111000011011111110111001111111111001111101111111100010110111111110110111001111111100100010111111110101111011111110101101111111111001011101111111011000111111111010000011111101111111111001000111111110011110111111100110101111110101100111111011010011100101111110001100111111011010111111001101111101110111111110010111001111111010110011111111010010111111111100100111111111101000111111110100000111111101101011111111110010101001111110101110"

In [132]:
import functools
#DECODER TEST
bin_DC = "111111111011001110111111111010010110111101000111111110000011001111110100011111111101000100111111010110001111100111011111110000010011111111010101101111111110011011001111111011101111111110011101111111100011101111111110101110001111111100110101111111111010010001111001011111101010111111111100010111111111111010000011111111100111111111111001110111111110111001111111101001101111101101111111111001101110111111100101101111111101110101111111001101111111101110111111111001111111111111010000111111111000011011111101000011111111010110110"
decoded = DC_decoder(bin_DC)
print(decoded)
encoded = DC_encoder(decoded)
print(encoded)
print(bin_DC == encoded)
print(sum(decoded))

[413, 563, 571, 328, 363, 431, 475, 475, 458, 335, 508, 361, 480, 446, 348, 532, 384, 529, 524, 567, 359, 490, 426, 392, 507, 545, 572, 427, 345, 462, 426, 485, 421, 488, 374, 390, 572]
111111111011001110111111111010010110111101000111111110000011001111110100011111111101000100111111010110001111100111011111110000010011111111010101101111111110011011001111111011101111111110011101111111100011101111111110101110001111111100110101111111111010010001111001011111101010111111111100010111111111111010000011111111100111111111111001110111111110111001111111101001101111101101111111111001101110111111100101101111111101110101111111001101111111101110111111111001111111111111010000111111111000011011111101000011111111010110110
True
16772


### AC

In [123]:
AC_Luminancia=[
['00','01', '100', '1011', '11010',
'111000', '1111000', '1111110110', '1111111110000010', '1111111110000011'],
['1100', '11011', '1111001', '111110110', '11111110110',
'1111111110000100', '1111111110000101', '1111111110000110', '1111111110000111', '1111111110001000'],
['11100', '11111001', '1111110111', '111111110100', '111111110001001',
'111111110001010', '111111110001011', '111111110001100', '111111110001101', '111111110001110'],
['111010', '111110111', '111111110101', '1111111110001111', '1111111110010000',
'1111111110010001', '1111111110010010', '1111111110010011', '1111111110010100', '1111111110010101'],
['111011', '1111111000', '1111111110010110', '1111111110010111', '1111111110011000',
'1111111110011001', '1111111110011010', '1111111110011011', '1111111110011100', '1111111110011101'],
['1111010', '11111110111', '1111111110011110', '1111111110011111', '1111111110100000',
'1111111110100001', '1111111110100010', '1111111110100011', '1111111110100100', '1111111110100101'],
['1111011', '111111110110', '1111111110100110', '1111111110100111', '1111111110101000',
'1111111110101001', '1111111110101010', '1111111110101011', '1111111110101100', '1111111110101101'],
['11111010', '111111110111', '1111111110101110', '1111111110101111', '1111111110110000',
'1111111110110001', '1111111110110010', '1111111110110011', '1111111110110100', '1111111110110101'],
['111111000', '111111111000000', '1111111110110110', '1111111110110111', '1111111110111000',
'1111111110111001', '1111111110111010', '1111111110111011', '1111111110111100', '1111111110111101'],
['111111001', '1111111110111110', '1111111110111111', '1111111111000000', '1111111111000001',
'1111111111000010', '1111111111000011', '1111111111000100', '1111111111000101', '1111111111000110'],
['111111010', '1111111111000111', '1111111111001000', '1111111111001001', '1111111111001010',
'1111111111001011', '1111111111001100', '1111111111001101', '1111111111001110', '1111111111001111'],
['1111111001', '1111111111010000', '1111111111010001', '1111111111010010', '1111111111010011',
'1111111111010100', '1111111111010101', '1111111111010110', '1111111111010111', '1111111111011000'],
['1111111010', '1111111111011001', '1111111111011010', '1111111111011011', '1111111111011100',
'1111111111011101', '1111111111011110', '1111111111011111', '1111111111100000', '1111111111100001'],
['11111111000', '1111111111100010', '1111111111100011', '1111111111100100', '1111111111100101',
'1111111111100110', '1111111111100111', '1111111111101000', '1111111111101001', '1111111111101010'],
['1111111111101011', '1111111111101100', '1111111111101101', '1111111111101110', '1111111111101111',
'1111111111110000', '1111111111110001', '1111111111110010', '1111111111110011', '1111111111110100'],
['1111111111110101', '1111111111110110', '1111111111110111', '1111111111111000',
'1111111111111001', '1111111111111010', '1111111111111011', '1111111111111101', '1111111111111110',
'1111111111111111']]

In [124]:
AC_Luminancia_reverse_dic = {}
z = 0
for l in AC_Luminancia:
    R = 0
    for element in l:
        AC_Luminancia_reverse_dic[element] = (z,R)
        R+=1
    z+=1
#print(AC_Luminancia_reverse_dic)
#AC_Luminancia_reverse_dic["00"]

In [121]:
def AC_encoder(listaAC):
    res = ""
    z = 0
    for x in listaAC:
        if x == 0: z+=1
        else :
            (R,C) = DC_table_inv(x)
            res += AC_Luminancia[z][R-1]#-1
            res += '{0:0b}'.format(C).zfill(R)
            z = 0
    return res+"1010"
def AC_decoder(bin_AC):
    res = []
    bits = ""
    i = 0
    while i < len(bin_AC):
        bits += bin_AC[i]
        i+=1
        if bits == "1010": return res
        try:
            (z,R) = AC_Luminancia_reverse_dic[bits]
        except KeyError:
            pass
        else:
            R+=1
            bits = ""
            C = int(bin_AC[i:i+R],2)
            i+=R
            res.extend([0]*z)
            res.append(DC_table(R,C))
    print("missing closure")
    return res

In [129]:
import functools
#import random
#ENCODER TEST
#for k in range(10):
    #listaAC = [(random.random()<0.1)*random.randrange(-50, 50) for t in range(10)]
listaAC = [9, 7, 0, 0, 0, 0, 1, -3, -7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8] 
encoded = AC_encoder(listaAC)
print(encoded)
decoded = AC_decoder(encoded)
print(decoded)
print(listaAC)
if functools.reduce(lambda i, j : i and j, map(lambda m, k: m == k, listaAC, decoded), True) : 
    print ("The lists are identical")
else :
    print ("The lists are not identical")

1011100110011111101110100100000111111111101001010001010
[9, 7, 0, 0, 0, 0, 1, -3, -7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8]
[9, 7, 0, 0, 0, 0, 1, -3, -7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8]
The lists are identical


In [130]:
import functools
#import random
#DECODER TEST
#for k in range(10):
    #listaAC = [(random.random()<0.1)*random.randrange(-50, 50) for t in range(10)]
bin_AC = "011110010111111111010100000010110111111111111001011010111111111111000111011010"
decoded = AC_decoder(bin_AC)
print(decoded)
encoded = AC_encoder(decoded)
print(encoded)
print(bin_AC)
if functools.reduce(lambda i, j : i and j, map(lambda m, k: m == k, bin_AC, encoded), True) : 
    print ("The lists are identical")
else :
    print ("The lists are not identical")

[3, 5, 0, 0, 0, -7, -1, -8, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5]
011110010111111111010100000010110111111111111001011010111111111111000111011010
011110010111111111010100000010110111111111111001011010111111111111000111011010
The lists are identical


### JPEG

In [31]:
Q_Luminance=np.array([
    [16 ,11, 10, 16,  24,  40,  51,  61],
    [12, 12, 14, 19,  26,  58,  60,  55],
    [14, 13, 16, 24,  40,  57,  69,  56],
    [14, 17, 22, 29,  51,  87,  80,  62],
    [18, 22, 37, 56,  68, 109, 103,  77],
    [24, 35, 55, 64,  81, 104, 113,  92],
    [49, 64, 78, 87, 103, 121, 120, 101],
    [72, 92, 95, 98, 112, 100, 103,  99]])

In [133]:
from scipy.fftpack import fft, dct, idct
import numpy as np
bloq = np.array([[71, 69, 59, 55, 59, 66, 86, 101], [77, 71, 63, 58, 65, 74, 89, 94], [79, 72, 67, 70, 75, 83, 92, 97], [85, 77, 74, 75, 78, 88, 98, 99], [81, 80, 85, 78, 79, 92, 102, 106], [80, 81, 91, 76, 78, 96, 102, 97], [85, 87, 99, 87, 94, 106, 105, 99], [119, 120, 128, 126, 126, 129, 126, 128]] ).astype("float")
bloq = bloq-128
print(bloq)
F = dct(bloq, axis = 0, norm = "ortho")
C = dct(F, axis = 1, norm = "ortho")
C = np.round(C/Q_Luminance,0) * Q_Luminance
resC = idct(C, axis = 1, norm = "ortho")
resF = idct(resC, axis = 0, norm = "ortho")
print(np.round(resF)+128)

[[-57. -59. -69. -73. -69. -62. -42. -27.]
 [-51. -57. -65. -70. -63. -54. -39. -34.]
 [-49. -56. -61. -58. -53. -45. -36. -31.]
 [-43. -51. -54. -53. -50. -40. -30. -29.]
 [-47. -48. -43. -50. -49. -36. -26. -22.]
 [-48. -47. -37. -52. -50. -32. -26. -31.]
 [-43. -41. -29. -41. -34. -22. -23. -29.]
 [ -9.  -8.   0.  -2.  -2.   1.  -2.   0.]]
[[ 70.  65.  57.  54.  59.  72.  86.  95.]
 [ 75.  70.  63.  61.  66.  77.  90.  99.]
 [ 76.  72.  67.  65.  70.  80.  91.  99.]
 [ 82.  79.  76.  75.  79.  87.  97. 103.]
 [ 87.  86.  84.  84.  88.  94. 101. 105.]
 [ 81.  80.  80.  81.  84.  89.  94.  97.]
 [ 90.  90.  91.  93.  96.  99. 102. 104.]
 [118. 119. 120. 123. 125. 128. 130. 131.]]


In [118]:
a = np.array([[78, 65, 52, 51, 62, 69, 60, 47],
 [65, 64, 55, 46, 52, 63, 57, 41],
 [52, 67, 65, 47, 44, 59, 58, 40],
 [45, 73, 78, 53, 44, 59, 61, 44],
 [39, 69, 79, 58, 44, 53, 55, 45],
 [36, 57, 69, 60, 46, 42, 43, 42],
 [42, 48, 60, 66, 55, 37, 35, 44],
 [51, 46, 58, 75, 65, 38, 34, 50]])

b = np.array([[78, 65, 52, 51, 62, 69, 60, 47], [65, 64, 55, 46, 52, 63, 57, 41], [52, 67, 65, 47, 44, 59, 58, 40], [45, 73, 78, 53, 44, 59, 61, 44], [39, 69, 79, 58, 44, 53, 55, 45], [36, 57, 69, 60, 46, 42, 43, 42], [42, 48, 60, 66, 55, 37, 35, 44], [51, 46, 58, 75, 65, 38, 34, 50]])

a==b

array([[ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True]])