### DC

In [1]:
import math

def DC_table(fila,columna):
    if fila == 0:
        return 0
    if columna >= 2**(fila-1):
        return columna
    else:
        return -(2**fila)+1+columna
   
   
def DC_table_inv(num):
    if num == 0:
        return (0,0)
    fila = math.floor(math.log2(abs(num)))+1
    if num > 0:
        columna = num
    else:
        columna = num +(2**fila)-1
    return fila,columna

In [26]:
def DC_encoder(listaDC):
    lista_diff = [listaDC[0]]
    for i in range(1,len(listaDC)):
        lista_diff.append(listaDC[i] - listaDC[i-1])
    res = ""
    for elem in lista_diff:
        (f,c) = DC_table_inv(elem)
        bin_f = "1"*f+"0"
        bin_c = ""
        if f != 0: bin_c = '{0:0b}'.format(c).zfill(f)
        res += bin_f + bin_c
    return res

def DC_decoder(bin_DC):
    res = []
    i = 0
    while i < len(bin_DC):
        f = 0
        c = 0
        bit = bin_DC[i]
        while bit == "1":
            f+=1
            i+=1
            bit = bin_DC[i]
        i+=1#skip the zero
        if f == 0:
            c = 0
        else:
            c = int(bin_DC[i:i+f],2)
        i+=f
        diff = DC_table(f,c)
        num = diff
        if res != []: num += res[-1]
        res.append(num)
    return res
        

In [119]:
import functools
#ENCODER TEST
listaDC = [94, 155, 29, 254, 215, 170, 240, 80, 9, 9, 197, 23, 89, 157, 81, 240, 11, 8, 226, 37, 172, 150, 237, 84, 140, 33, 239, 70, 23, 224, 32, 92, 109, 202]
encoded = DC_encoder(listaDC)
print(encoded)
decoded = DC_decoder(encoded)
print(decoded)
if functools.reduce(lambda i, j : i and j, map(lambda m, k: m == k, listaDC, decoded), True) : 
    print ("The lists are identical")
else :
    print ("The lists are not identical")

11111110101111011111101111011111111000000011111111101110000111111100110001111110010010111111101000110111111110010111111111111001110000111111110101111001111111100101000111111110100001011111110100010011111110011001111111111010011111111111110000110101100011111111011011010111111110010000101111111101000011111111001001111111101010111111111110011001101111110111000111111100010100111111110110011101111111100101011011111100100001111111101100100111111111000111111111111011110011111010001111111101011101
[94, 155, 29, 254, 215, 170, 240, 80, 9, 9, 197, 23, 89, 157, 81, 240, 11, 8, 226, 37, 172, 150, 237, 84, 140, 33, 239, 70, 23, 224, 32, 92, 109, 202]
The lists are identical


In [23]:
a = "1111111101110101011111110101001111111110010111111111100001011111111011000101111001111111111011001001111110011001011111111001110001111111110110100101111000011111110001000111111000011011111110111001111111111001111101111111100010110111111110110111001111111100100010111111110101111011111110101101111111111001011101111111011000111111111010000011111101111111111001000111111110011110111111100110101111110101100111111011010011100101111110001100111111011010111111001101111101110111111110010111001111111010110011111111010010111111111100100111111111101000111111110100000111111101101011111111110010101001111110101110"
b = "1111111101110101011111110101001111111110010111111111100001011111111011000101111001111111111011001001111110011001011111111001110001111111110110100101111000011111110001000111111000011011111110111001111111111001111101111111100010110111111110110111001111111100100010111111110101111011111110101101111111111001011101111111011000111111111010000011111101111111111001000111111110011110111111100110101111110101100111111011010011100101111110001100111111011010111111001101111101110111111110010111001111111010110011111111010010111111111100100111111111101000111111110100000111111101101011111111110010101001111110101110"

In [126]:
import functools
#DECODER TEST
bin_DC = "111111111101000000001111100101111111110101011001111111100111100011111100000001111110101001111111110110011010111111100000000111111101001110111110111111111111100101101111111110100111111111110001100111111110100001111111110011110111111111010001111111101011111111110010010011111110101001111111101110010111111110011101011111111101100010011111110011001011111110011101011111110100111011111110001110011111011111111111101100010111111100000011111111110101011011111111000010011111011001111111000001111110001111111110100010011111110010100111111100110011"
decoded = DC_decoder(bin_DC)
print(decoded)
encoded = DC_encoder(decoded)
print(encoded)
print(bin_DC == encoded)
print(sum(decoded))

[513, 503, 675, 540, 477, 518, 723, 723, 596, 674, 705, 541, 620, 518, 585, 519, 662, 673, 491, 532, 646, 508, 704, 627, 558, 636, 537, 568, 666, 542, 715, 597, 609, 489, 483, 620, 577, 501]
111111111101000000001111100101111111110101011001111111100111100011111100000001111110101001111111110110011010111111100000000111111101001110111110111111111111100101101111111110100111111111110001100111111110100001111111110011110111111111010001111111101011111111110010010011111110101001111111101110010111111110011101011111111101100010011111110011001011111110011101011111110100111011111110001110011111011111111111101100010111111100000011111111110101011011111111000010011111011001111111000001111110001111111110100010011111110010100111111100110011
True
22371


### AC

In [123]:
AC_Luminancia=[
['00','01', '100', '1011', '11010',
'111000', '1111000', '1111110110', '1111111110000010', '1111111110000011'],
['1100', '11011', '1111001', '111110110', '11111110110',
'1111111110000100', '1111111110000101', '1111111110000110', '1111111110000111', '1111111110001000'],
['11100', '11111001', '1111110111', '111111110100', '111111110001001',
'111111110001010', '111111110001011', '111111110001100', '111111110001101', '111111110001110'],
['111010', '111110111', '111111110101', '1111111110001111', '1111111110010000',
'1111111110010001', '1111111110010010', '1111111110010011', '1111111110010100', '1111111110010101'],
['111011', '1111111000', '1111111110010110', '1111111110010111', '1111111110011000',
'1111111110011001', '1111111110011010', '1111111110011011', '1111111110011100', '1111111110011101'],
['1111010', '11111110111', '1111111110011110', '1111111110011111', '1111111110100000',
'1111111110100001', '1111111110100010', '1111111110100011', '1111111110100100', '1111111110100101'],
['1111011', '111111110110', '1111111110100110', '1111111110100111', '1111111110101000',
'1111111110101001', '1111111110101010', '1111111110101011', '1111111110101100', '1111111110101101'],
['11111010', '111111110111', '1111111110101110', '1111111110101111', '1111111110110000',
'1111111110110001', '1111111110110010', '1111111110110011', '1111111110110100', '1111111110110101'],
['111111000', '111111111000000', '1111111110110110', '1111111110110111', '1111111110111000',
'1111111110111001', '1111111110111010', '1111111110111011', '1111111110111100', '1111111110111101'],
['111111001', '1111111110111110', '1111111110111111', '1111111111000000', '1111111111000001',
'1111111111000010', '1111111111000011', '1111111111000100', '1111111111000101', '1111111111000110'],
['111111010', '1111111111000111', '1111111111001000', '1111111111001001', '1111111111001010',
'1111111111001011', '1111111111001100', '1111111111001101', '1111111111001110', '1111111111001111'],
['1111111001', '1111111111010000', '1111111111010001', '1111111111010010', '1111111111010011',
'1111111111010100', '1111111111010101', '1111111111010110', '1111111111010111', '1111111111011000'],
['1111111010', '1111111111011001', '1111111111011010', '1111111111011011', '1111111111011100',
'1111111111011101', '1111111111011110', '1111111111011111', '1111111111100000', '1111111111100001'],
['11111111000', '1111111111100010', '1111111111100011', '1111111111100100', '1111111111100101',
'1111111111100110', '1111111111100111', '1111111111101000', '1111111111101001', '1111111111101010'],
['1111111111101011', '1111111111101100', '1111111111101101', '1111111111101110', '1111111111101111',
'1111111111110000', '1111111111110001', '1111111111110010', '1111111111110011', '1111111111110100'],
['1111111111110101', '1111111111110110', '1111111111110111', '1111111111111000',
'1111111111111001', '1111111111111010', '1111111111111011', '1111111111111101', '1111111111111110',
'1111111111111111']]

In [124]:
AC_Luminancia_reverse_dic = {}
z = 0
for l in AC_Luminancia:
    R = 0
    for element in l:
        AC_Luminancia_reverse_dic[element] = (z,R)
        R+=1
    z+=1
#print(AC_Luminancia_reverse_dic)
#AC_Luminancia_reverse_dic["00"]

In [121]:
def AC_encoder(listaAC):
    res = ""
    z = 0
    for x in listaAC:
        if x == 0: z+=1
        else :
            (R,C) = DC_table_inv(x)
            res += AC_Luminancia[z][R-1]#-1
            res += '{0:0b}'.format(C).zfill(R)
            z = 0
    return res+"1010"
def AC_decoder(bin_AC):
    res = []
    bits = ""
    i = 0
    while i < len(bin_AC):
        bits += bin_AC[i]
        i+=1
        if bits == "1010": return res
        try:
            (z,R) = AC_Luminancia_reverse_dic[bits]
        except KeyError:
            pass
        else:
            R+=1
            bits = ""
            C = int(bin_AC[i:i+R],2)
            i+=R
            res.extend([0]*z)
            res.append(DC_table(R,C))
    print("missing closure")
    return res

In [125]:
import functools
#import random
#ENCODER TEST
#for k in range(10):
    #listaAC = [(random.random()<0.1)*random.randrange(-50, 50) for t in range(10)]
listaAC = [8, 8, 9, 0, 0, 0, 9, -2, -6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7] 
encoded = AC_encoder(listaAC)
print(encoded)
decoded = AC_decoder(encoded)
print(decoded)
print(listaAC)
if functools.reduce(lambda i, j : i and j, map(lambda m, k: m == k, listaAC, decoded), True) : 
    print ("The lists are identical")
else :
    print ("The lists are not identical")

10111000101110001011100111111111100011111001010110000111111111101111111111010
[8, 8, 9, 0, 0, 0, 9, -2, -6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7]
[8, 8, 9, 0, 0, 0, 9, -2, -6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7]
The lists are identical


In [128]:
import functools
#import random
#DECODER TEST
#for k in range(10):
    #listaAC = [(random.random()<0.1)*random.randrange(-50, 50) for t in range(10)]
bin_AC = "1001100011000011110111111000111111111011011110001010"
decoded = AC_decoder(bin_AC)
print(decoded)
encoded = AC_encoder(decoded)
print(encoded)
print(bin_AC)
if functools.reduce(lambda i, j : i and j, map(lambda m, k: m == k, bin_AC, encoded), True) : 
    print ("The lists are identical")
else :
    print ("The lists are not identical")

[6, 1, -6, 0, 0, 0, 0, 1, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 8]
1001100011000011110111111000111111111011011110001010
1001100011000011110111111000111111111011011110001010
The lists are identical


### JPEG

In [31]:
Q_Luminance=np.array([
    [16 ,11, 10, 16,  24,  40,  51,  61],
    [12, 12, 14, 19,  26,  58,  60,  55],
    [14, 13, 16, 24,  40,  57,  69,  56],
    [14, 17, 22, 29,  51,  87,  80,  62],
    [18, 22, 37, 56,  68, 109, 103,  77],
    [24, 35, 55, 64,  81, 104, 113,  92],
    [49, 64, 78, 87, 103, 121, 120, 101],
    [72, 92, 95, 98, 112, 100, 103,  99]])

In [127]:
from scipy.fftpack import fft, dct, idct
import numpy as np
bloq = np.array([[55, 91, 80, 54, 74, 50, 48, 49], [57, 94, 64, 66, 54, 43, 39, 39], [108, 123, 64, 60, 46, 40, 42, 43], [126, 136, 75, 44, 43, 41, 48, 48], [130, 123, 61, 41, 46, 46, 44, 45], [118, 86, 43, 41, 42, 42, 42, 60], [88, 48, 46, 43, 47, 57, 75, 76], [48, 60, 52, 66, 77, 82, 73, 68]]).astype("float")
bloq = bloq-128
print(bloq)
F = dct(bloq, axis = 0, norm = "ortho")
C = dct(F, axis = 1, norm = "ortho")
C = np.round(C/Q_Luminance,0) * Q_Luminance
resC = idct(C, axis = 1, norm = "ortho")
resF = idct(resC, axis = 0, norm = "ortho")
print(np.round(resF)+128)

[[-73. -37. -48. -74. -54. -78. -80. -79.]
 [-71. -34. -64. -62. -74. -85. -89. -89.]
 [-20.  -5. -64. -68. -82. -88. -86. -85.]
 [ -2.   8. -53. -84. -85. -87. -80. -80.]
 [  2.  -5. -67. -87. -82. -82. -84. -83.]
 [-10. -42. -85. -87. -86. -86. -86. -68.]
 [-40. -80. -82. -85. -81. -71. -53. -52.]
 [-80. -68. -76. -62. -51. -46. -55. -60.]]
[[ 53.  81.  80.  62.  62.  57.  48.  53.]
 [ 70.  90.  79.  58.  58.  52.  40.  43.]
 [103. 107.  80.  54.  55.  49.  36.  39.]
 [134. 121.  77.  46.  50.  47.  38.  46.]
 [138. 115.  65.  35.  42.  44.  42.  56.]
 [112.  92.  50.  31.  43.  44.  45.  65.]
 [ 77.  68.  46.  44.  60.  57.  55.  76.]
 [ 55.  57.  51.  61.  80.  72.  66.  86.]]


In [118]:
a = np.array([[78, 65, 52, 51, 62, 69, 60, 47],
 [65, 64, 55, 46, 52, 63, 57, 41],
 [52, 67, 65, 47, 44, 59, 58, 40],
 [45, 73, 78, 53, 44, 59, 61, 44],
 [39, 69, 79, 58, 44, 53, 55, 45],
 [36, 57, 69, 60, 46, 42, 43, 42],
 [42, 48, 60, 66, 55, 37, 35, 44],
 [51, 46, 58, 75, 65, 38, 34, 50]])

b = np.array([[78, 65, 52, 51, 62, 69, 60, 47], [65, 64, 55, 46, 52, 63, 57, 41], [52, 67, 65, 47, 44, 59, 58, 40], [45, 73, 78, 53, 44, 59, 61, 44], [39, 69, 79, 58, 44, 53, 55, 45], [36, 57, 69, 60, 46, 42, 43, 42], [42, 48, 60, 66, 55, 37, 35, 44], [51, 46, 58, 75, 65, 38, 34, 50]])

a==b

array([[ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True]])